webserver/django/mydjango_board/board/urls.py
from django.urls import path

from . import views

app_name = "board"


urlpatterns = [
    path("", views.board_list_html, name="board_list_html"),
    path("comments/", views.comment_list, name="comment_list"),
    # django에서는 <>를 변수로 인식하고, 함수의 인자로 전달된다. 이름은 동일해야한다.
    path("<int:board_id>/", views.board_detail_html, name="board_detail_html"),
    path("write/", views.board_create, name="write"),
    path("<int:board_id>/modify", views.board_modify_html, name="modify"),
    path("<int:board_id>/delete", views.board_delete, name="delete"),
]

webserver/django/mydjango_board/mydjango_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("user/", include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# settings.STATIC_URL

webserver/django/mydjango_board/user/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.index, name = 'index'),
]

webserver/django/mydjango_board/board/models.py
from django.db import models
from django.utils import timezone

from django.core import validators

# Create your models here.

# python manage.py migrate board 0005
# 0005로 rollback 해준다.


class Board(models.Model):
    id = models.AutoField(primary_key=True)  # integer(auto-increment)
    title = models.CharField(
        "제목",
        max_length=255,  # varchar(255)
        validators=[validators.MinLengthValidator(2, "최소 세 글자 이상은 입력해주셔야 합니다.")],
    )
    author = models.CharField(max_length=255)
    content = models.TextField(
        "내용", validators=[validators.MinLengthValidator(10, "최소 10글자 이상은 입력해주셔야 합니다.")]
    )  # text
    created_at = models.DateTimeField(auto_now_add=True)  # 추가될 때 default로 현재시간
    updated_at = models.DateTimeField(auto_now=True)  # 추가/업데이트 될 때 default로 현재시간

    # 이렇게 하면 admin에서 board title 보임
    def __str__(self):
        return self.title

    # 아래꺼로 해도 title 보여야 하는데... 잘 모르겠음
    # def __repr__(self):
    #     return self.title

    # @property  # https://www.daleseo.com/python-property/
    # def to_html(self):
    #     return f"""
    # """


class Comment(models.Model):
    # id 없어도 자동으로 만들어준다.
    # id = models.AutoField(primary_key=True)  # integer(auto-increment)

    # related_name="comment_set"은 기본값, 그래서 board.comment_set 하면 이게 불러와진다.
    # Board.comment_set 하면 해당 board의 comment들 불러온다.
    # n에서 1을 불러오는것보다 1에서 n을 불러오는 경우가 많기 때문에 있는 기능.
    # 이 이름은 바꿀 수 있다
    board = models.ForeignKey(
        Board, null=True, on_delete=models.SET_NULL, related_name="comment_set"
    )
    content = models.CharField(max_length=255)  # varchar(255)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)  # 추가될 때 default로 현재시간
    updated_at = models.DateTimeField(auto_now=True)  # 추가/업데이트 될 때 default로 현재시간

webserver/django/mydjango_board/board/forms.py
from django import forms
from .models import Board


class BoardForm(forms.ModelForm):
    # __ : private
    # _ : protected
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()

    class Meta:
        model = Board
        fields = ["title", "content", "author"]
        widgets = {"title": forms.TextInput(attrs={"placeholder": "제목을 입력해주세요"})}

    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

webserver/django/mydjango_board/board/views.py
from django.shortcuts import render, redirect, reverse
from .models import Board, Comment

# Create your views here.

from django.http import HttpResponse


def index(request):
    # 인자로 전달하는 변수가 흐름 내에서 유지되면 context라고 부른다.
    sample_list = range(10)
    return render(request, "board/index.html", {"name": "유저", "sample": sample_list})


def comment_list(request):
    comment_list = Comment.objects.all()
    ret = "<ul>"
    for comment in comment_list:
        ret += f"<li>{comment.id} | {comment.content} | {comment.board_id}"
    ret += "</ul>"
    return HttpResponse(ret)


# ===========================================


def board_list_html(request):
    board_list = Board.objects.prefetch_related("comment_set").all()
    li = []
    for board in board_list:
        li.append(
            {
                "id": board.id,
                "title": board.title,
                "content": board.content,
                "com_cnt": len(board.comment_set.all()),
                "date": board.created_at,
            }
        )
    return render(request, "board/boardList.html", {"info": li})


def board_detail_html(request, board_id):
    if request.method == "POST":
        data = request.POST
        comment = data.get("comment")
        if len(comment) > 0:
            Comment.objects.create(
                board_id=board_id, content=comment, author=request.user
            )
        # index 페이지로 이동
        return redirect(reverse("board:board_detail_html", args=[board_id]))

    board = Board.objects.prefetch_related("comment_set").get(pk=board_id)
    date = board.created_at
    print(board.updated_at)
    if board.created_at != board.updated_at:
        date = board.updated_at
    info = {
        "id": board.id,
        "title": board.title,
        "content": board.content,
        "comment": board.comment_set.all(),
        "com_len": len(board.comment_set.all()),
        "date": date,
    }
    return render(request, "board/boardDetail.html", {"info": info})


def board_modify_html(request, board_id):
    if request.method == "POST":
        data = request.POST
        title, content = data["title"], data["content"]

        board = Board.objects.get(id=board_id)
        board.title = title
        board.content = content
        board.save()
        return redirect(reverse("board:modify", args=[board_id]))

    # elif request.methd == 'GET':
    board = Board.objects.prefetch_related("comment_set").get(id=board_id)

    info = {
        "id": board.id,
        "title": board.title,
        "content": board.content,
        "comment": board.comment_set.all(),
        "com_len": len(board.comment_set.all()),
        "date": board.created_at,
    }
    return render(request, "board/boardModify.html", {"info": info})


def board_delete(request, board_id):
    board = Board.objects.get(pk=board_id)
    board.delete()
    return redirect(reverse("board:board_list_html"))


def write_html(request):
    return render(request, "board/boardWrite.html")


################################################
# 게시글 등록하기
from .forms import BoardForm


def board_create(request):
    form = BoardForm()
    if request.method == "POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("board:board_list_html"))
    return render(request, "board/boardwrite.html", {"form": form})


# def board_create(request):
#     if request.method == "POST":
#         data = request.POST
#         title, content = data["title"], data.get("content")
#         Board.objects.create(title=title, content=content, author=request.user)
#         # index 페이지로 이동
#         return redirect(
#             reverse(
#                 "board:board_list_html",
#             )
#         )
#     return render(request, "board/boardwrite.html")

webserver/django/mydjango_board/user/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import json
from json2html import *


# request : <WSGIRequest: GET '/user/'>
# <WSGIRequest: GET '/user/'>
# <class 'django.core.handlers.wsgi.WSGIRequest'>
def index(request):
    sample_list = range(10)
    return render(request, "board/index.html", {"name": "유저", "sample": sample_list})

webserver/django/mydjango_board/board/templates/board/boardDetail.html
{% extends "./partials/base.html" %} {% block title %}
<title>Detail</title>
{% endblock %} {% block main %}
<div style="margin: 0.3rem">
    <div>
        <a style="font-weight: bold; font-size: 2rem">{{info.title}}</a>
        <a style="float: right">{{info.date}}</a>
    </div>
    <hr class="my-4" />
    <div>
        <h5 style="font-weight: bold">{{info.content}}</h5>
    </div>
    <div>
        <a href="delete">
            <button
                type="button"
                class="btn btn-outline-danger"
                style="float: right">
                삭제
            </button>
        </a>
        <a href="modify">
            <button
                type="button"
                class="btn btn-outline-warning"
                style="float: right; margin-right: 1%">
                수정
            </button>
        </a>
    </div>

    <div style="margin-top: 7%">
        <h5>댓글 ({{info.com_len}})</h5>
        <hr class="my-4" />
        <form action="" method="POST">
            {% csrf_token %}

            <div class="input-group">
                <textarea
                    class="form-control"
                    name="comment"
                    id="comment-input"
                    rows="3"></textarea>
                <button type="submit" class="btn btn-outline-success">
                    작성
                </button>
            </div>
        </form>
        {% for com in info.comment %}
        <div style="margin-top: 1.5%">
            <a>{{com.content}}</a>
            <a style="float: right">{{com.created_at}}</a>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

webserver/django/mydjango_board/board/templates/board/boardList.html
{% extends "./partials/base.html" %} {% block main %}
<div style="margin: 0.3rem">
    <a style="font-weight: bold; font-size: 2rem">게시글</a>

    <a href="write/">
        <button type="button" class="btn btn-outline-warning" style="float: right">게시글 작성</button>
    </a>
</div>
<div class="list-group">
    {% for i in info %}
    <a href="{{i.id}}" class="list-group-item list-group-item-action d-flex justify-content-between">
        <div>
            <h5>{{i.title}}</h5>
            <span>{{i.content}}</span>
        </div>
        <div style="float: right">
            <span class="d-flex">{{i.date}}</span>
            <span class="badge bg-warning-subtle text-warning-emphasis rounded-pill" style="float: right">{{i.com_cnt}}</span>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

webserver/django/mydjango_board/board/templates/board/boardModify.html
{% extends "./partials/base.html" %} {% block title %}
<title>Write</title>
{% endblock title %} {% block main %}
<div style="margin: 1.5rem; margin-left: 20%; margin-right: 20%">
    <a style="font-weight: bold; font-size: 2rem">게시글 수정</a>
    <hr class="my-4" />
    <form action="" method="POST">
        {% csrf_token %}
        <div class="board-header p-3 mb-3">
            <label for="title-input" class="form-label">글 제목</label>
            <input
                type="text"
                name="title"
                class="form-control"
                id="title-input"
                placeholder="글 제목을 입력해주세요."
                value="{{info.title}}" />
        </div>
        <div class="board-content p-3 mb-3">
            <label for="content-input" class="form-label">내용</label>
            <textarea
                class="form-control"
                name="content"
                id="content-input"
                rows="10">
                {{info.content}}
            </textarea>
        </div>

        <div class="mb-3 p-3">
            <div style="float: right">
                <button type="submit" class="btn btn-outline-success">
                    수정
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

webserver/django/mydjango_board/board/templates/board/boardwrite.html
{% extends "./partials/base.html" %} {% block title %}
<title>Write</title>
{% endblock title %} {% block main %}
<div style="margin: 1.5rem; margin-left: 20%; margin-right: 20%">
    <a style="font-weight: bold; font-size: 2rem">게시글 작성</a>
    <hr class="my-4" />
    {% comment %} action은 비워두면 defalut가 현재 url {% endcomment %}
    <form action="{% url 'board:write' %}" method="POST">
        {% csrf_token %} {% comment %}
        <div class="board-header p-3 mb-3">
            <label for="title-input" class="form-label">글 제목</label>
            <input
                type="text"
                name="title"
                class="form-control"
                id="title-input"
                placeholder="글 제목을 입력해주세요." />
        </div>
        <div class="board-content p-3 mb-3">
            <label for="content-input" class="form-label">내용</label>
            <textarea
                class="form-control&quot; name=&quot;content&quot; id=&quot;content-input&quot; rows=10"></textarea>
        </div>
        {% endcomment %} {% for field in form %}
        <div class="fieldWrapper m-2">
            {{ field.label_tag }} {{ field }} {% for error in field.errors %}
            <div id="content-help" class="form-text text-danger">
                {{ field.errors }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}

        <div class="mb-3 p-3">
            <div style="float: right">
                <button type="submit" class="btn btn-outline-success">
                    작성
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

webserver/django/mydjango_board/board/templates/board/index.html
{% extends "./partials/base.html" %} {% block main %}
<div style="margin: 0.3rem">
    <a style="font-weight: bold; font-size: 2rem">게시글</a>
    <button type="button" class="btn btn-outline-warning" style="float: right">게시글 작성</button>
</div>
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">게시글 1</h5>
            <small>3 days ago</small>
        </div>
        <p class="mb-1">내용 1</p>
        <small>박민지</small>
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">게시글 2</h5>
            <small class="text-muted">3 days ago</small>
        </div>
        <p class="mb-1">내용 2</p>
        <small class="text-muted">박민지</small>
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">게시글 3</h5>
            <small class="text-muted">3 days ago</small>
        </div>
        <p class="mb-1">내용 3</p>
        <small class="text-muted">박민지</small>
    </a>
</div>
{% endblock %}

webserver/django/mydjango_board/board/templates/board/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block title %}
        <title>Board</title>
        {% endblock %} <link href={% static "bootstrap\css\bootstrap.min.css" %}
        rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous" />
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }

            main > .container {
                padding: 60px 15px 0;
            }
        </style>
    </head>

    <body>
        <!-- navigation bar -->

        {% include "./header.html" %}

        <main class="container">{% block main %}{% endblock %}</main>

        {% include "./footer.html" %}
    </body>
</html>

webserver/django/mydjango_board/board/templates/board/partials/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>

webserver/django/mydjango_board/board/templates/board/partials/header.html
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center">
            <button type="button" class="btn btn-warning">Navbar</button>

            <ul
                class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li>
                    <a href="/board" class="nav-link px-2 text-white">
                        전체 게시글
                    </a>
                </li>
                <li>
                    <a href="/board/write" class="nav-link px-2 text-white">
                        Write
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link px-2 text-secondary">
                        Disabled
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link px-2 text-secondary">
                        Dropdown
                    </a>
                </li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input
                    type="search"
                    class="form-control form-control-dark text-bg-dark"
                    placeholder="Search..."
                    aria-label="Search" />
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-outline-light me-2">
                    Login
                </button>
                <button type="button" class="btn btn-warning">Sign-up</button>
            </div>
        </div>
    </div>
</header>